/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    ApproveCheckModal: typeof import('./src/components/ApproveCheckModal.vue')['default']
    BalanceCard: typeof import('./src/components/BalanceCard.vue')['default']
    CreateCheckModal: typeof import('./src/components/CreateCheckModal.vue')['default']
    CreatePurchaseModal: typeof import('./src/components/CreatePurchaseModal.vue')['default']
    DefaultCard: typeof import('./src/components/DefaultCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
  }
}
