/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    BalanceCard: typeof import('./src/components/BalanceCard.vue')['default']
    CardStatisticsVertical: typeof import('./src/components/CardStatisticsVertical.vue')['default']
    copy: typeof import('./src/components/CreateCheckModal copy.vue')['default']
    CreateCheck: typeof import('./src/components/CreateCheck.vue')['default']
    CreateCheckModal: typeof import('./src/components/CreateCheckModal.vue')['default']
    CreatePurchaseModal: typeof import('./src/components/CreatePurchaseModal.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    DefaultCard: typeof import('./src/components/DefaultCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PaginatedTable: typeof import('./src/components/PaginatedTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
    Transactions: typeof import('./src/components/Transactions.vue')['default']
    TranslationTable: typeof import('./src/components/TranslationTable.vue')['default']
  }
}
